---
deployment:
      tasks:
        - export DEPLOYPATH=/home/mininfrv/public_html  # Add /<app_folder> if required
        - cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
