name: Create Issue for Bitcoin Cash Foundation Weekly News

on:
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at 12:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  check-bch-news:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Debug: List repository contents
      - name: List repository contents
        run: |
          echo "Current directory: $(pwd)"
          ls -R .github
          echo "Checking for check_bch_news.py:"
          find . -name check_bch_news.py

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install feedparser requests

      # Run script to check RSS feed and create issue
      - name: Check for new BCH Weekly News
        env:
          GITHUB_TOKEN: ${{ secrets.BCHF_WEEKLY_NEWS }} # Uses BCHF_WEEKLY_NEWS secret
        run: |
          python .github/scripts/check_bch_news.py